version: 1
basemodel:
  dino:
    model_path: ./Model/vit_base_obj365_all_teacher_224.pth
    decode_idx: 0
    input_key: img_224
    vit_output_shape:
    - 768
    - 14
    - 14
  vit:
    model_path: ./Model/vit-b-16_224-224-fp32.pth
    decode_idx: 1
    input_key: img_224
    vit_output_shape:
    - 768
    - 14
    - 14
middle_blur:
  enable: True
  min_width: 10
  max_width: 15
  blur_radius: 5
data:
  public_neg_extend: false
  train:
  - dataset_path: ./DATA/Zhujian
    label_remap:
      pair: 0
      unpair: 1
    list_file: Train.txt
    images_path: ./DATA/Zhujian/images_labels
    labels_path: ./DATA/Zhujian/images_labels
    obj_name: obj.names
  transforms:
    ColorJitter:
      brightness: 0.5
      contrast: 0
      hue: 0
      saturation: 0
      turn_on: true
    RandomAffine:
      degrees: 10
      scale:
      - 0.9
      - 1.1
      shear: 10
      translate:
      - 0.1
      - 0.0
      turn_on: true
    RandomEqualize:
      prob: 0.1
      turn_on: false
    RandomGrayscale:
      prob: 0.1
      turn_on: false
    RandomHorizontalFlip:
      prob: 0.5
      turn_on: true
    gaussianblur:
      g_bulr_kernel: 5
      g_bulr_sigma:
      - 0.1
      - 2
      turn_on: false
  valid:
  - dataset_path: ./DATA/Zhuajian
    label_remap:
      pair: 0
      unpair: 1
    list_file: Val.txt
    images_path: ./DATA/Zhuajian/images_labels_val
    labels_path: ./DATA/Zhuajian/images_labels_val
    obj_name: obj.names
gpu_ids: '2'
loss: focal
loss_params:
  alpha:
  - 10
  - 10
  gamma: 2
  num_classes: 2
model:
  Block_params:
    attn_drop: 0.1
    dim: 256
    drop_path: 0.1
    init_values: null
    mlp_ratio: 4.0
    num_heads: 8
    proj_drop: 0.1
    qk_norm: true
    qkv_bias: false
  cls_num: 2
  decoder_key: Slips_Only_v11
  num_layers: 6
optimizer:
  lr: 0.001
  lr_adjust:
    decay_ep: 5
    decay_val: 0.9
    min_val: 0.0001
  momentum: 0.9
  type: adamw
entrophy_config:
  lambda_value: 0
train_param:
  epoch: 100
  save_dir: ./ckpts/stage1
  t_batch: 128
  v_batch: 16