# This file contains some useful functions for the project.
import os
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import seaborn as sns
import random
import math
from sklearn.manifold import TSNE
from matplotlib.gridspec import GridSpec
from matplotlib.colors import LinearSegmentedColormap
from generator import FractureCurveGenerator
from scipy import optimize


def load_training_data(path, new_data=False, parameter_list=[187, 1, 3, 0.02, 500]):
    """
    Description: This function is used to load the training data
    path: path to the data
    new_data: whether to generate new data
    parameter_list: parameters for the physics engine
    """
    if new_data:
        # Physics engine generates data
        # default parameters (187, 1, 3, 0.02, 500)
        generator = FractureCurveGenerator(parameter_list)
        vectors = generator.get_fracture_curves(6000)
    else:
        # Import data (generated by physics engine)
        vectors = np.load(path)
    return vectors


def get_top_k_accuracy(k, f_model, c_model, str, direction):
    """
    Description: This function is used to calculate the top k accuracy of the model
    k: top k
    f_model: feature extraction model
    c_model: comparison model
    str: path to the data
    direction: "longitudinal" or "transverse"
    """
    # calculate the top k accuracy
    top_k = 0
    dis_map = get_heat_map(f_model, c_model, str, 118, False)
    length = len(dis_map)
    gather_list_transverse = []
    for i in range(length):
        dis_list = []
        if direction == "longitudinal":
            dis_list = [x[i] for x in dis_map]
        else:
            dis_list = dis_map[i].copy()
        dis_list.sort()
        top_index = dis_list.index(dis_map[i][i])
        gather_list_transverse.append(top_index + 1)

    for j in gather_list_transverse:
        if j <= k:
            top_k += 1

    return top_k


def calculate_position_stats_numpy(list1, list2, list3):
    """
    Description: This function is used to calculate the mean and standard deviation of three lists using numpy
    """
    # transform to numpy array
    arrays = np.array([list1, list2, list3])

    # calculate mean and standard deviation
    means = np.mean(arrays, axis=0)
    stds = np.std(arrays, axis=0, ddof=1)

    means = np.round(means, 2)
    stds = np.round(stds, 2)

    return means.tolist(), stds.tolist()


def inference(f_model, c_model, vector_1, vector_2):
    """
    Description: This function is used to calculate the distance between two vectors
    f_model: feature extraction model
    c_model: comparison model
    vector_1: input vector 1
    vector_2: input vector 2
    """
    f_model.eval()
    c_model.eval()
    feature_1 = f_model(vector_1)
    feature_2 = f_model(vector_2)
    dis = c_model(torch.stack((feature_1, feature_2), 1))
    return dis


def get_heat_map(f_model, c_model, str, length, isshow=False):
    """
    Description: This function is used to calculate the heat map of the model
    """
    # calculate the heat map
    f_model.eval()
    c_model.eval()

    real_vectors = np.load(str)
    real_vectors = real_vectors[:, 2:4, :].astype(np.float32)

    dis_map = []
    for i in range(length):
        dis_list = []
        for j in range(length):
            v1 = real_vectors[i, 0, :][np.newaxis, np.newaxis, :]
            v2 = real_vectors[j, 1, :][np.newaxis, np.newaxis, :]
            v1[0][0] = [x - v1.min() for x in v1[0][0]]
            v2[0][0] = [x - v2.min() for x in v2[0][0]]
            v1 /= v1.max() + 1e-6
            v2 /= v2.max() + 1e-6
            v1 = torch.tensor(v1, dtype=torch.float32)
            v2 = torch.tensor(v2, dtype=torch.float32)
            dis = inference(f_model, c_model, v1, v2)
            dis_list.append(dis.item())

        dis_map.append(dis_list)

    return dis_map


def get_tsne_plots(fake_vectors, real_vectors, dis_map):
    """
    Generate t-SNE visualization and matching quality heatmap,
    save them separately, and export data as Excel
    """

    # Create output directory
    os.makedirs("outputs", exist_ok=True)

    # Data preprocessing function
    def extract_vectors(vectors, sample_size, indices=(2, 3)):
        top = vectors[:, indices[0] : indices[0] + 1, :].astype(np.float32)
        bottom = vectors[:, indices[1] : indices[1] + 1, :].astype(np.float32)
        return [vec[0] for vec in top[:sample_size]], [vec[0] for vec in bottom[:sample_size]]

    # Extract fake and real data
    fake_top, fake_bottom = extract_vectors(fake_vectors, 1000)
    real_top, real_bottom = extract_vectors(real_vectors, 118)

    # Combine bottom data for t-SNE
    combined_bottom = np.vstack((fake_bottom, real_bottom))

    # t-SNE transformation
    tsne = TSNE(n_components=2, random_state=42)
    data_transformed = tsne.fit_transform(combined_bottom)

    # Set standard plotting style
    plt.style.use("seaborn-whitegrid")
    plt.rcParams.update(
        {
            "font.family": "Arial",
            "font.size": 10,
            "axes.linewidth": 1.0,
            "axes.grid": False,
            "axes.facecolor": "white",
            "figure.facecolor": "white",
            "figure.dpi": 300,
        }
    )

    # Separate data
    synthetic_data = data_transformed[:1000]
    real_data = data_transformed[1000:]

    # Save t-SNE data to Excel
    tsne_df = pd.DataFrame(
        {
            "Type": ["Synthetic"] * len(synthetic_data) + ["Real"] * len(real_data),
            "Dimension_1": np.concatenate([synthetic_data[:, 0], real_data[:, 0]]),
            "Dimension_2": np.concatenate([synthetic_data[:, 1], real_data[:, 1]]),
        }
    )
    tsne_df.to_excel("outputs/tsne_data.xlsx", index=False)

    # Save heatmap data to Excel
    dis_map_df = pd.DataFrame(dis_map)
    dis_map_df.to_excel("outputs/heatmap_data.xlsx", index=False)

    # save t-SNE plot
    plt.figure(figsize=(5, 5))

    # Blue-green color scheme used in the reference
    plt.scatter(
        synthetic_data[:, 0],
        synthetic_data[:, 1],
        c="#1f77b4",  # Blue
        s=20,
        alpha=0.6,
        edgecolors="none",
        label="Synthetic data",
    )

    plt.scatter(
        real_data[:, 0], real_data[:, 1], c="#2ca02c", s=20, alpha=0.6, edgecolors="none", label="Real data"  # Green
    )

    # Complete border
    for spine in plt.gca().spines.values():
        spine.set_visible(True)
        spine.set_linewidth(0.8)

    # Add legend with border
    legend = plt.legend(loc="upper right", markerscale=1, frameon=True)
    legend.get_frame().set_edgecolor("#E3E3E3")  # Add gray border
    legend.get_frame().set_linewidth(0.8)  # Set border width

    # Remove axis labels and title
    plt.xlabel("")
    plt.ylabel("")
    plt.title("")

    # Set ticks but hide labels
    plt.xticks([-60, -30, 0, 30, 60], [])
    plt.yticks([-60, -30, 0, 30, 60], [])

    plt.tight_layout()
    plt.savefig("outputs/tsne_plot.pdf", bbox_inches="tight")
    plt.savefig("outputs/tsne_plot.png", dpi=300, bbox_inches="tight")
    plt.close()

    # save heatmap plot
    plt.figure(figsize=(5, 5))

    # Modify color scheme, use gradient from deep blue to white
    cmap = LinearSegmentedColormap.from_list(
        "match_quality", ["#053061", "#2166AC", "#4393C3", "#92C5DE", "#F7F7F7"], N=100
    )

    # Draw heatmap
    ax = sns.heatmap(
        dis_map,
        cmap=cmap,
        square=True,
        vmin=0.0,  # Ensure minimum value starts from 0
        vmax=1.0,  # Ensure maximum value ends at 1
        cbar_kws={"shrink": 0.8, "aspect": 15, "label": ""},
        xticklabels=False,
        yticklabels=False,
    )

    # Keep clean layout
    plt.tight_layout()
    plt.savefig("outputs/heatmap_plot.pdf", bbox_inches="tight")
    plt.savefig("outputs/heatmap_plot.png", dpi=300, bbox_inches="tight")
    plt.close()
